on:
  push:
     branches:
       - main


name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown", "dplyr", "printr", "ggplot2", "magrittr", "tidyr", "purrr", "knitr", "kableExtra", "tibble", "readr", "ape", "maps"))'
      - name: Render Book as gitbook
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
      - name: Render Book as epub
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book")'
      # - name: Render Book as pdfbook
      #   run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
          # path: docs/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
         # path: docs # optional
     - name: Deploy to GitHub Pages
       # uses: Cecilapp/GitHub-Pages-deploy@v3
       uses: Cecilapp/GitHub-Pages-deploy@v2
       env:
          # GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          BUILD_DIR: _book/                     # "_site/" by default
       # with:
       #    email: ${{ secrets.EMAIL }  # must be a verified email
       #    build_dir: docs     # "_site/" by default
       #    jekyll: no
